const projects = [
  // {
  //  title: "Firebase cms",
  // },
  // {
  //  title: "Booho clone",
  //  description:
  //   "A clone of Boohoo Fashion UK. A client facing ecommerce web application built on Nodejs, Nextjs and Google Firebase Services.",
  //  techStack: [
  //   "Firebase Auth",
  //   "Nextjs",
  //   "Nodejs",
  //   "Firebase Hosting",
  //   "Firebase Cloud Functions",
  //   "Firebase Firestore",
  //   "Typescript",
  //  ],
  //  features: ["xxgx", "xxexx", "xxtxx", "xxgjx", "xxppx", "xxffx", "xdsx"],
  //  links: {
  //   sourceCode: "xxxx",
  //   websiteUrl: "",
  //   youtubeDemo: "xxxx",
  //  },
  //  gifSrcUrl: "",
  //  videoSrcUrl: "",
  // },
  // {
  //  title: "Boohoo CMS",
  //  description:
  //   "A fully featured Content Management System for Bohoo-Clone. An ecommerce platform built on Node, Nextjs and Google Firebase Services.",
  //  techStack: [
  //   "Firebase Auth",
  //   "Nextjs",
  //   "Nodejs",
  //   "Firebase Hosting",
  //   "Firebase Cloud Functions",
  //   "Firebase Firestore",
  //   "Typescript",
  //  ],
  //  features: ["xuixx", "xoixx", "sexxx", "xxkhx", "xgddxx", "xxggdx", "xxrexx"],
  //  links: {
  //   sourceCode: "xxxx",
  //   websiteUrl: "xxxx",
  //   youtubeDemo: "xxxx",
  //  },
  //  gifSrcUrl: "",
  //  videoSrcUrl: "",
  // },
  {
   title: "ISMAILOPATOLA.IO",
   description:
    "My professional frontend developer portfolio and blogging website",
   techStack: [
    "React",
    "Gatsby",
    "Netlify",
    "Contentful",
    "Material UI",
    "Sass",
    "React-Helmet",
    "Google-analytics",
   ],
   features: [
    "Blog",
    "Responsive UI",
    "SEO",
    "Analytics",
    "AXE Accessibility Test",
    "Linting",
    "Social Share",
    "Social Comment with Discus",
   ],
   links: {
    sourceCode: "https://github.com/Ismail-Opatola/my-website",
    websiteUrl: "",
    youtubeDemo: "",
   },
   gifSrcUrl: undefined,
   videoSrcUrl: undefined,
  },
  {
   title: "WUR",
   description:
    "Would-You-Rather App. A project Inspired by Udacity's React Developer Nano Degree programe. This app was part of the capstone projects.",
   techStack: [
    "Firebase Auth",
    "React",
    "Redux",
    "Express",
    "Firebase Hosting",
    "Firebase Cloud Functions",
    "Firebase Firestore",
    "Material UI",
   ],
   features: [
    "Responsive UI",
    "User Authentication",
    "User Role & Authorization",
    "User Profile",
    "User Generated Survey",
    "User Generated Polls",
    "LeaderBorad",
    "Real-time Notification",
   ],
   links: {
    sourceCode: "https://github.com/Ismail-Opatola/wur-react-firebase-client",
    websiteUrl: "https://would-you-rather-app-c5895.firebaseapp.com",
    youtubeDemo: "https://www.youtube.com/embed/P-AXYkmut_M",
   },
   gifSrcUrl: "wur",
   videoSrcUrl: "https://www.youtube.com/embed/P-AXYkmut_M",
  },
  {
   title: "Fit Tracker",
   description:
    "A Triathlon, Fitness Tracking mobile app built with React Native.",
   techStack: ["React", "React-Native", "Expo", "Redux"],
   features: [
    "Daily Routine Check",
    "Record workout, meal & sleep routine",
    "Real-Time Speed Tracking",
    "Real-Time Distance Tracking",
    "Navigation Compass",
    "Calender",
    "Push Notification",
   ],
   links: {
    sourceCode: "https://github.com/Ismail-Opatola/fit_tracker_app-",
    websiteUrl: "https://expo.io/@turfff/fit_tracker",
    youtubeDemo:"https://www.youtube.com/embed/cq1pXukBJHU",
   },
   gifSrcUrl: "fit_tracker",
   videoSrcUrl: "https://www.youtube.com/embed/cq1pXukBJHU",
  },
  // {
  //  title: "Estatement",
  //  description:
  //   "A demo - real estate management and architectural business website built with Gatsby and Netlify service.",
  //  techStack: [
  //   "Gatsby",
  //   "React",
  //   "Markdown",
  //   "Reactstrap",
  //   "Bootstrap",
  //   "Netlify",
  //  ],
  //  features: ["Responsive UI", "SEO", "LazyLoad Image"],
  //  links: {
  //   sourceCode: "https://github.com/Ismail-Opatola/estatement_website",
  //   websiteUrl: "https://inspiring-gates-7b3e39.netlify.com/",
  //   youtubeDemo: "",
  //  },
  //  gifSrcUrl: "",
  //  videoSrcUrl: "",
  // },
  {
   title: "MyReads",
   description:
    "A Book listing app which pulls data from Google Books API. A project Inspired by Udacity's React Developer Nano Degree programe. This app was part of the capstone projects.",
   techStack: ["React", "Google Books API", "Netlify"],
   features: [
    "Book Search",
    "Book list Categories",
    "Book Search filter",
    "Responsive UI",
    "SEO",
    "LazyLoad Image",
    "API-Request",
   ],
   links: {
    sourceCode: "https://github.com/Ismail-Opatola/react-project-myreads-app",
    websiteUrl: "https://myreads-app-v0.netlify.com/",
    youtubeDemo: "https://www.youtube.com/embed/knhODYnXX30",
   },
   gifSrcUrl: "myreads",
   videoSrcUrl: "https://www.youtube.com/embed/knhODYnXX30",
  },
 ],
 skills = {
  programming: ["Javascript 100%", "Typescripts 60%", "HTML 100%", "CSS 100%"],
  techStack: [
   "React 100%",
   "React Native 80%",
   "Nodejs 90%",
   "MongoDB 80%",
   "Express 90%",
   "Firebase 90%",
   "Gatsby 90%",
   "Nextjs 80%",
   "GraphQL 70%",
   "SCSS 90%",
   "Material-UI 90%",
   "Contentful",
   "Shopify",
   "GSAP",
  ],
  tools: [
   "Git 100%",
   "Vscode",
   "Adobe XD 100%",
   "Inkscape 70%",
   "Vim 50%",
   "Genymotion",
   "Bluestack",
   "VirtualBox",
   "Axe-Accessibilty",
   "Postman",
   "Google Web Console",
   "Google Analytics 50%",
   "SEMrush",
   "Mailchimp",
  ],
 }

const notes = { projects, skills }
module.exports = notes
